---
title: 'Copy Number and Non-Synonymous Mutation Analysis - cfDNA cohort'
author: 'Pierre Levy'
format:
  html:
    code-fold: true
engine: knitr
execute:
  echo: false
  message: false
  warning: false
date: '`r Sys.Date()`'
---
```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(GenVisR)
library(ComplexHeatmap)
library(circlize)
library(GenomicRanges)
library(vcfR)

setwd("/Users/plevy/Library/CloudStorage/OneDrive-VHIO/labagros/pierre/proj/collab/andrea/cfDNA_cohort_rtoledo/")
```

```{r}
# Load data
# Patients
patients_IMN <- readLines("patients_IMN.txt")
# exclude non baseline and screening failure samples
non_baseline <- c("IMN019", "IMN084")
screen_fail <- c("IMN1502")
patients_IMN <- patients_IMN[!patients_IMN %in% c(non_baseline, screen_fail)]
patients_GOI <- readLines("patients_GOI.txt")
patients <- c(patients_IMN, patients_GOI)

patient_grep <- paste(patients, collapse = "|") # regex expression to match files containing patient name later

#  Metadata
metadata <- fread("metadata_WES-cfDNA.tsv")
# add GOI patients
# Create new rows with "x", "y", "z" in the first column and NA in all other columns
new_rows <- as.data.frame(matrix(NA, nrow = 8, ncol = ncol(metadata)))
colnames(new_rows) <- colnames(metadata)  # Ensure column names match
new_rows$Sample_ID <- patients_GOI  # Assign values to the first column
new_rows$Tumor_group <- c("Breast", "Breast", "H&N", "H&N", "GI_CRC", "GI_CRC", "Skin", "Skin")
new_rows$MSI_MSS_status <- c("Not done", "Not done", "Not done", "Not done", "MSI", "Not done", "Not done", "Not done")
# Bind new rows to the existing data frame
metadata <- rbind(metadata, new_rows)


# FILTERS
min_tvaf <- 0.03
min_alt <- 4
min_cov <- 9
min_callers_snv <- 2
min_callers_indels <- 2
```


# Non-Synonymous Mutations
## cfDNA cohort (Oncoanalyser re-filtered results)
```{r}
# Gather relaxed filter files
directory_path <- "/Volumes/datos_lab/hmftools/cfDNA_rtoledo"
files_cfDNA <- system2("find", args = c(directory_path, "-name", "*sage.somatic.refiltered.pave.vcf.gz"), stdout = TRUE)


directory_path <- "/Volumes/datos_lab/hmftools/GOI_cfDNA"
files_GOI <- system2("find", args = c(directory_path, "-name", "*sage.somatic.refiltered.pave.vcf.gz"), stdout = TRUE)

files <- c(files_cfDNA, files_GOI)
files <- files[grepl(patient_grep, files)]

patients_oncoanalyser <- gsub("/Volumes/datos_lab/hmftools/cfDNA_rtoledo/(IMN\\d+|TMB\\d+).*vcf.gz", "\\1", files)
patients_oncoanalyser <- gsub("/Volumes/datos_lab/hmftools/GOI_cfDNA/(.*)/pave/.*vcf.gz", "\\1", patients_oncoanalyser)
named_files <- setNames(as.list(files), patients_oncoanalyser)
named_files <- named_files[patients] # Reorder

```

```{r}
# Function to create table with data from all each sample
get_pave <- function(x, y) { # The y is necessary for the purrr::imap function later to access the names of the elements of the named list
    # Process VCF (combined calls) to extract variant infos
    vcf <- read.vcfR(x)
    vcf_tib <- vcfR2tidy(vcf, info_only = FALSE)

    variants <- vcf_tib$fix %>%
        dplyr::select(ChromKey, CHROM, POS, REF, ALT, FILTER, IMPACT, QUAL) %>%
        mutate(patient = y)
    
    # Extract VAF, ALT counts and coverage (for tumor and normal separate)
    vaf_table_tumor <- vcf_tib$gt %>%
     dplyr::filter(Indiv == paste0(y, "CFDNA")) %>% 
     mutate(
        tVAF = gt_AF,
        tALT = as.numeric(gsub("\\d+,", "", gt_AD)),
        tCOV = gt_DP
        ) %>% 
     dplyr::select(ChromKey, POS, tVAF, tALT, tCOV)

    vaf_table_normal <- vcf_tib$gt %>%
     dplyr::filter(Indiv == paste0(y, "N")) %>% 
     mutate(
        nVAF = gt_AF,
        nALT = as.numeric(gsub("\\d+,", "", gt_AD)),
        nCOV = gt_DP
        ) %>% 
     dplyr::select(ChromKey, POS, nVAF, nALT, nCOV)

    # Merge info
    variants <- variants %>% left_join(vaf_table_tumor, by = c("ChromKey", "POS")) %>% left_join(vaf_table_normal, by = c("ChromKey", "POS")) %>% distinct(ChromKey, POS, .keep_all = TRUE)

    ## Filter NSM (missense, nonsense, frameshift)
    variants <- variants %>%
        rowwise() %>%
        dplyr::filter(str_detect(IMPACT, "MISSENSE|NONSENSE|FRAMESHIFT|STOP_LOST|INFRAME|missense_variant|inframe_insertion|inframe_deletion|stop_lost|frameshift_variant")) %>%
        mutate(variant_type = ifelse(nchar(REF) == 1 & nchar(ALT) == 1, "SNV", "INDEL"))

# variants <- variants %>% filter(FILTER == "PASS", QUAL >= 35, ifelse(tALT == 2, tVAF >= 0.05, tVAF >= 0.04))
# variants2 <- variants %>% filter(FILTER == "PASS", QUAL >= 35, tVAF >= 0.05)

    # Filter out variants not meeting coverage/depth/vaf criteria
    variants <- variants %>% dplyr::filter(nCOV >= min_cov, tCOV >= min_cov, tVAF >= min_tvaf, tALT >= min_alt)
    # Filter out PON, PONGnomad, PONArtefact variants
    variants <- variants %>% dplyr::filter(FILTER == "PASS")

    # Select useful columns 
    variants <- variants %>% dplyr::select(CHROM, POS, REF, ALT, FILTER, IMPACT, patient, variant_type, tVAF, tALT, tCOV, nVAF, nALT, nCOV)

    # Ensure the structure is consistent even if no variants are found
    if (nrow(variants) == 0) {
        variants <- tibble(
            CHROM = character(), POS = numeric(), REF = character(), ALT = character(),
            FILTER = character(), IMPACT = character(), patient = character(),
            variant_type = character(), tVAF = numeric(), tALT = numeric(), tCOV = numeric(), nVAF = numeric(), nALT = numeric(), nCOV = numeric()
        )
    }

    return(variants)
}

# Apply to all patients
list_pave <- purrr::imap(named_files, get_pave)

# Merge
pave_table <- list_pave %>%
    bind_rows()

# Write pave table
write.table(pave_table, file = "20250825_pave_table.tsv", sep = "\t", row.names = FALSE, quote = FALSE)

# # Load pave table
# pave_table <- fread("20250825_pave_table.tsv")
```

# Copy Number Data (ASCAT)
```{r}
#  Gather Copy Number files
directory_path <- "/Volumes/datos_lab/ascat"
files <- system2("find", args = c(directory_path, "-name", "*segments_raw.txt"), stdout = TRUE)
files <- sort(files[grepl(patient_grep, files)])
files <- files[!grepl("force_ploidy|FrTu|TIL012/TIL012|TIL015/TIL015", files)]

patients_ascat <- gsub("/Volumes/datos_lab/ascat/(.*)/.*segments_raw.txt", "\\1", files)
patients_ascat <- gsub("/hg38_NeoPred", "", patients_ascat)
named_files <- setNames(as.list(files), patients_ascat)
named_files <- named_files[patients] # Reorder

# # Check patients for which we have both ascat and neopred
# # Combine patterns into one regex
# intersect_neopred_ascat <- intersect(patients_ascat, patients_neopred)
# combined_pattern <- paste(intersect_neopred_ascat, collapse = "|")
# # Check matches
# select_files <- files[grepl(combined_pattern, files)]

format_cna <- function(segments_raw, exclude_sex_chromosomes = TRUE, min_segment_size = 500000) {
	# Load data
    segs <- fread(segments_raw) %>% mutate(
        nMajor = as.numeric(nMajor),
        nMinor = as.numeric(nMinor)
    )

	# Create CN matrix for heatmap
	cna_seg <- segs
    colnames(cna_seg)[colnames(cna_seg) == "nMajor"] <- paste0(unique(cna_seg$sample), "_CN_major")
    colnames(cna_seg)[colnames(cna_seg) == "nMinor"] <- paste0(unique(cna_seg$sample), "_CN_minor")
    colnames(cna_seg)[colnames(cna_seg) == "startpos"] <- "start"
    colnames(cna_seg)[colnames(cna_seg) == "endpos"] <- "end"
    cna_seg <- cna_seg %>% dplyr::select(chr, start, end, paste0(unique(cna_seg$sample), "_CN_major"), paste0(unique(cna_seg$sample), "_CN_minor"))

	# Calculate percentage of genome affected by SCNA
	# Normalize chromosome names (in case of "chrX", "chrY", etc.)
	segs$chr <- gsub("^chr", "", segs$chr)
	# Convert chromosome column to character for filtering
	segs$chr <- as.character(segs$chr)
	# Optionally exclude sex chromosomes
	if (exclude_sex_chromosomes) {
	segs <- segs[!(segs$chr %in% c("X", "Y")), ]
	}
	# Add segment length
	segs$length <- segs$endpos - segs$startpos + 1
	# Filter out short segs
	segs <- segs[segs$length >= min_segment_size, ]
	# Calculate total copy number
	segs$total_cn <- segs$nMajor + segs$nMinor
	# Define altered segs (any deviation from diploid)
	altered_segs <- segs[segs$total_cn != 2, ]
	# Compute total and altered genome length
	total_length <- sum(segs$length)
	altered_length <- sum(altered_segs$length)
	# Compute SCNA burden percentage
	scna_percent <- (altered_length / total_length) * 100
	# Make it a df
	scna_percent_df <- data.frame(sample = unique(segs$sample), scna_percent = round(scna_percent, 2))

	# Return outputs as list
    return(list(scna_mat = cna_seg, scna_tbl = scna_percent_df))
   
}

# Apply to all patients
list_cna_mat_percent <- purrr::map(named_files, format_cna)
# Get list of cna matrices
list_cna <- list_cna_mat_percent %>% purrr::map("scna_mat")
# Make table of cna percent for all patients
percent <- list_cna_mat_percent %>% purrr::map("scna_tbl") %>% bind_rows()

# write table cna percent
write.table(percent, file = "20250825_cna_percent.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```

   
# ComplexHeatmap plots
```{r}
    # Get chromosome ranges from circlize package (read.chromInfo()$df) and make a GRanges object of the chromosome lengths
chr_df <- read.chromInfo()$df
chr_df <- chr_df[chr_df$chr %in% paste0("chr", c(1:22, "X")), ]
chr_df$chr <- gsub("chr", "", chr_df$chr) # Only if needed to remove the "chr" prefix, depends on reference genome used
chr_gr <- GRanges(seqnames = chr_df[, 1], ranges = IRanges(chr_df[, 2] + 1, chr_df[, 3]))
chr_gr

chr_window <- EnrichedHeatmap::makeWindows(chr_gr, w = 1e6)
chr_window
chr_window
```

```{r}
average_in_window <- function(window, gr, v, method = "weighted", empty_v = NA) {
    if (missing(v)) v <- rep(1, length(gr))
    if (is.null(v)) v <- rep(1, length(gr))
    if (is.atomic(v) && is.vector(v)) v <- cbind(v)

    v <- as.matrix(v)
    if (is.character(v) && ncol(v) > 1) {
        stop("`v` can only be a character vector.")
    }

    if (length(empty_v) == 1) {
        empty_v <- rep(empty_v, ncol(v))
    }

    u <- matrix(rep(empty_v, each = length(window)), nrow = length(window), ncol = ncol(v))

    mtch <- as.matrix(findOverlaps(window, gr))
    intersect <- pintersect(window[mtch[, 1]], gr[mtch[, 2]])
    w <- width(intersect)
    v <- v[mtch[, 2], , drop = FALSE]
    n <- nrow(v)

    ind_list <- split(seq_len(n), mtch[, 1])
    window_index <- as.numeric(names(ind_list))
    window_w <- width(window)

    if (is.character(v)) {
        for (i in seq_along(ind_list)) {
            ind <- ind_list[[i]]
            if (is.function(method)) {
                u[window_index[i], ] <- method(v[ind], w[ind], window_w[i])
            } else {
                tb <- tapply(w[ind], v[ind], sum)
                u[window_index[i], ] <- names(tb[which.max(tb)])
            }
        }
    } else {
        if (method == "w0") {
            gr2 <- reduce(gr, min.gapwidth = 0)
            mtch2 <- as.matrix(findOverlaps(window, gr2))
            intersect2 <- pintersect(window[mtch2[, 1]], gr2[mtch2[, 2]])

            width_intersect <- tapply(width(intersect2), mtch2[, 1], sum)
            ind <- unique(mtch2[, 1])
            width_setdiff <- width(window[ind]) - width_intersect

            w2 <- width(window[ind])

            for (i in seq_along(ind_list)) {
                ind <- ind_list[[i]]
                x <- colSums(v[ind, , drop = FALSE] * w[ind]) / sum(w[ind])
                u[window_index[i], ] <- (x * width_intersect[i] + empty_v * width_setdiff[i]) / w2[i]
            }
        } else if (method == "absolute") {
            for (i in seq_along(ind_list)) {
                u[window_index[i], ] <- colMeans(v[ind_list[[i]], , drop = FALSE])
            }
        } else if (method == "weighted") {
            for (i in seq_along(ind_list)) {
                ind <- ind_list[[i]]
                u[window_index[i], ] <- colSums(v[ind, , drop = FALSE] * w[ind]) / sum(w[ind])
            }
        } else {
            if (is.function(method)) {
                for (i in seq_along(ind_list)) {
                    ind <- ind_list[[i]]
                    u[window_index[i], ] <- method(v[ind], w[ind], window_w[i])
                }
            } else {
                stop("wrong method.")
            }
        }
    }

    return(u)
}

# Convert CNA data to GRange objects matrix
mat <- matrix(nrow = 3030, ncol = 0)
for (i in 1:length(list_cna)) {
    gr_cna <- GRanges(seqnames = list_cna[[i]]$chr, ranges = IRanges(list_cna[[i]]$start, list_cna[[i]]$end))
    v <- as.matrix(list_cna[[i]][, -(1:3)])
    num_mat <- average_in_window(chr_window, gr_cna, v, method = "absolute", empty_v = NA)
    mat <- cbind(mat, num_mat)
}

dim(mat)
head(mat)
```

```{r}
chr <- as.vector(seqnames(chr_window))
chr_level <- paste0(c(1:22, "X"))
chr <- factor(chr, levels = chr_level)
```

### Oncoanalyser Heatmap (Only Re-filtered results) 
```{r}
set.seed(4)

# Summary table NSM
summary_NSM_pave_refilt <- pave_table %>%
    group_by(patient) %>%
    summarise(NSM = n(), median_tVAF = median(as.numeric(tVAF)))
summary_NSM_pave_refilt <- full_join(data.frame(patient = patients_oncoanalyser), summary_NSM_pave_refilt, by = "patient")
summary_NSM_pave_refilt[is.na(summary_NSM_pave_refilt)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.
summary_NSM_pave_refilt <- full_join(data.frame(patient = patients), summary_NSM_pave_refilt, by = "patient") # keep NAs: meaning not analysed with Oncoanalyser

    # Summary table SNV
summary_SNV_pave_refilt <- pave_table %>%
    dplyr::filter(variant_type == "SNV") %>%
    group_by(patient) %>%
    summarise(SNV = n(), median_tVAF = median(as.numeric(tVAF)))
summary_SNV_pave_refilt <- full_join(data.frame(patient = patients_oncoanalyser), summary_SNV_pave_refilt, by = "patient")
summary_SNV_pave_refilt[is.na(summary_SNV_pave_refilt)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.
summary_SNV_pave_refilt <- full_join(data.frame(patient = patients), summary_SNV_pave_refilt, by = "patient") # keep NAs: meaning not analysed with Oncoanalyser

    # Summary table INDEL
summary_INDEL_pave_refilt <- pave_table %>%
    dplyr::filter(variant_type == "INDEL") %>%
    group_by(patient) %>%
    summarise(INDEL = n(), median_tVAF = median(as.numeric(tVAF)))
summary_INDEL_pave_refilt <- full_join(data.frame(patient = patients_oncoanalyser), summary_INDEL_pave_refilt, by = "patient")
summary_INDEL_pave_refilt[is.na(summary_INDEL_pave_refilt)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.
summary_INDEL_pave_refilt <- full_join(data.frame(patient = patients), summary_INDEL_pave_refilt, by = "patient") # keep NAs: meaning not analysed with Oncoanalyser

# metadata
meta <- metadata %>% dplyr::filter(Sample_ID %in% patients_oncoanalyser)
# Apply a cap of 200 to matrix (to sum SNV+INDEL but respect proportions)
# Capping function
cap_and_transform <- function(row, max_sum = 200) {
    if (all(is.na(row))) {
        return(row)  # Return the row unchanged if it only contains NA
    }
    
    total <- sum(row, na.rm = TRUE)  # Ignore NAs in the sum
    if (total > max_sum) {
        factor <- max_sum / total
        row[!is.na(row)] <- row[!is.na(row)] * factor  # Scale only non-NA values
    }
    
    return(row)
}

# NSMs Re-Filtered
annot_NSM_vaf_df_refilt <- summary_NSM_pave_refilt %>%
    dplyr::filter(patient %in% patients_oncoanalyser)
snv_indel_mat_refilt <- summary_SNV_pave_refilt %>%
    dplyr::select(patient, SNV) %>%
    left_join(summary_INDEL_pave_refilt %>% dplyr::select(patient, INDEL), by = "patient") %>%
    dplyr::filter(patient %in% patients_oncoanalyser)
snv_indel_mat_refilt[is.na(snv_indel_mat_refilt)] <- 0 # replace NAs by 0 when no INDELs in patient
snv_indel_mat_refilt <- as.matrix(snv_indel_mat_refilt %>% dplyr::select(-patient))
transformed_mat_refilt <- t(apply(snv_indel_mat_refilt, 1, cap_and_transform))

# color for annot (VAF, TF, target lesion sum)
col_msi <- colorRamp2(c(0,10), c("white", "#FFB90F"))
col_vaf <- colorRamp2(c(5, 25), c("white", "#FF3E96"))
col_tf <- colorRamp2(c(0, 0.7), c("white", "#8B4513"))
col_lesion <- colorRamp2(c(0, 300), c("white", "#FF7256"))

tumor_group_colors <- c(
    GU = "#FF6F00FF", Lung = "#C71000FF", "H&N" = "#008EA0FF",
    Mesothelioma = "#8A4198FF", Skin = "#A5927D", GI_CRC = "#FF6348FF",
    GI_nonCRC = "#84D7E1FF", Breast = "#FF95A8FF", "NET/Thyroid" = "#3D3B25FF",
    "Bone and Soft Tissue Tumors / Craniovertebral Tumors" = "#ADE2D0FF",
    Gyn = "#1A5354FF", "Sarcoma/Unk" = "#3F4041FF",
    "NA" = "gray"  # Add explicit color for NA values
)
hepatic_mets_colors <- setNames(
    c(paletteer::paletteer_d("nbapalettes::raptors_city")[1:length(na.omit(unique(meta$`Hepatic_met?`)))], "gray"), 
    c(na.omit(unique(meta$`Hepatic_met?`)), "NA")
)
msi_colors <- setNames(
    c(paletteer::paletteer_d("ltc::fernande")[1:length(na.omit(unique(meta$MSI_MSS_status)))], "gray"), 
    c(na.omit(unique(meta$MSI_MSS_status)), "NA")
)
col_percent_scna <- colorRamp2(c(0, 100), c("white", "#008B45"))

# Create a vector for NSM numbers interleaving with empty strings, to annotate every other column
NSM_annot_refilt <- rep("", length(annot_NSM_vaf_df_refilt$NSM) * 2) # Preallocate a vector with empty strings
NSM_annot_refilt[seq(2, length(NSM_annot_refilt), 2)] <- annot_NSM_vaf_df_refilt$NSM # Fill every odd index with the original values

# Same for RIO patient code
RIO_annot <- rep("", length(meta$RIO_ID) * 2) # Preallocate a vector with empty strings
RIO_annot[seq(1, length(RIO_annot), 2)] <- meta$RIO_ID # Fill every odd index with the original values

column_ha <- HeatmapAnnotation(
    # "360RIO" = anno_text(RIO_annot, location = 0.1, just = "left", gp = gpar(fontsize = 10, col = "grey50"), show_name = TRUE),
	"TMB_txt_refilt" = anno_text(NSM_annot_refilt, location = 0.1, just = "left", gp = gpar(fontsize = 10, col = "grey30")),
    "TMB" = anno_barplot(transformed_mat_refilt[rep(1:nrow(snv_indel_mat_refilt), each = 2), ], bar_width = 1, gp = gpar(fill = c("#00C5CD", "blue"), col = c("#00C5CD", "blue"))),
    "Median tVAF" = rep(annot_NSM_vaf_df_refilt$median_tVAF * 100, each = 2),
    "Tumor Fraction" = rep(as.numeric(meta$TF_value), each = 2),
    # "Target Lesion Sum (mm)" = rep(as.numeric(meta$`Target_lesion_summ(mm)`), each = 2),
    # "Hepatic Mets" = rep(meta$`Hepatic_met?` , each = 2),
    "Tumor Group" = rep(meta$Tumor_group, each = 2),
    # "Sex" = rep(meta$Gender, each = 2),
    "MSI status" = rep(meta$MSI_MSS_status, each = 2),
	"SCNA (% of genome)" = rep(percent$scna_percent, each = 2),
    col = list(`Median tVAF` = col_vaf, `Tumor Fraction` = col_tf, `Target Lesion Sum (mm)` = col_lesion, `Tumor Group` = tumor_group_colors, `Hepatic Mets` = hepatic_mets_colors, `MSI status` = msi_colors, `MSIsensor-pro` = col_msi, `SCNA (% of genome)` = col_percent_scna),
    annotation_name_side = "left", annotation_name_gp = gpar(col = "grey20", fontsize = 10),
	simple_anno_size = unit(0.5, "cm")
)

TMB_legend <- Legend(labels = c("SNV", "INDEL"), title = "TMB", legend_gp = gpar(fill = c("#00C5CD", "blue")))

# Order columns
# By NSM
order_columns <- annot_NSM_vaf_df_refilt %>%
    arrange(NSM) %>%
    pull(patient)
# #  By Tumor Group
# order_columns <- meta %>%
#     arrange(Tumor_group) %>%
#     pull(Sample_ID)
# #  By TF
# order_columns <- meta %>%
#     arrange(TF_value) %>%
#     pull(Sample_ID)
# #  By Median tVAF
# order_columns <- annot_NSM_vaf_df %>%
#     arrange(median_tVAF) %>%
#     pull(patient)

heatmap_colors <- structure(c("#00868B", "grey98 ", "#B77FE2", "#7D26CD"), names = c("0", "1", "2", "3"))
mat <- pmin(mat, 3)
mat <- round(mat, 0)

# change labels patients: 
patient_label <- gsub("GOIGROS0", "GOI-", order_columns)
patient_label <- gsub("GOI-08", "GOI-06", patient_label)
patient_label <- gsub("Motricolor002", "GOI-05", patient_label)
patient_label <- gsub("TIL012", "GOI-07", patient_label)
patient_label <- gsub("TIL015", "GOI-08", patient_label)


hm <- Heatmap(mat,
    name = "Allelic Copy Number", top_annotation = column_ha, col = heatmap_colors,
    row_split = chr, cluster_rows = FALSE, cluster_columns = FALSE, column_split = factor(rep(patients, each = 2), levels = order_columns, labels = patient_label),
    show_column_names = FALSE,
    # column_title = NULL,
    column_title_rot = 90, column_title_gp = gpar(fontsize = 10),
    row_title_rot = 0, row_title_gp = gpar(fontsize = 7), border = TRUE,
    row_gap = unit(0, "points"), column_gap = unit(0, "points"), border_gp = gpar(col = "grey50", lwd = 0.5),
    heatmap_legend_param = list(at = c("0", "1", "2", "3"), labels = c("0", "1", "2", "3+"))
)
pdf("heatmap_cfDNA_cohort_FINAL.pdf", width = 15, height = 8)
draw(hm, annotation_legend_list = list(TMB_legend), merge_legend = FALSE)
dev.off()
```

## GOI cohort Heatmap (Jared's/Neopred TMB)

#### Load ASCAT data (with FrTu)
```{r}
#  Gather files
directory_path <- "/Volumes/datos_lab/ascat"
files <- system2("find", args = c(directory_path, "-name", "*segments_raw.txt"), stdout = TRUE)
files <- files[grepl("GOI|TIL012|TIL015|Motri", files)]
files <- files[!grepl("force_ploidy|TIL012/TIL012|TIL015/TIL015", files)]

# Extract subject IDs
subject_ids <- gsub(".*/ascat/([^/]+)/.*", "\\1", files)

# Define the desired order
desired_order <- c("GOIGROS001", "GOIGROS002", "GOIGROS003", "GOIGROS004", 
                   "Motricolor002", "GOIGROS008", "TIL012", "TIL015")

# Create a factor for ordering
subject_factor <- factor(subject_ids, levels = desired_order, ordered = TRUE)

# Order files based on subject order
ordered_files <- files[order(subject_factor, files)]
ordered_ids <- gsub(".*/ascat/([^/]+)/.*", "\\1", ordered_files)

# Apply to all patients
list_cna_mat_percent <- purrr::map(ordered_files, format_cna)
# Get list of cna matrices
list_cna <- list_cna_mat_percent %>% purrr::map("scna_mat")
# Make table of cna percent for all patients
percent <- list_cna_mat_percent %>% purrr::map("scna_tbl") %>% bind_rows()


# convert to a GRanges object
mat_GOI <- matrix(nrow = 3030, ncol = 0)
for (i in 1:length(list_cna)) {
    gr_cna <- GRanges(seqnames = list_cna[[i]]$chr, ranges = IRanges(list_cna[[i]]$start, list_cna[[i]]$end))
    v <- as.matrix(list_cna[[i]][, -(1:3)])
    num_mat <- average_in_window(chr_window, gr_cna, v, method = "absolute", empty_v = NA)
    mat_GOI <- cbind(mat_GOI, num_mat)
}
```

#### Variant Calling Heatmap
```{r}
set.seed(4)
# ccf_table load (Variant Calling)
ccf_table <- fread("/Users/plevy/Library/CloudStorage/OneDrive-VHIO/labagros/pierre/proj/collab/andrea/CCF_plots/variant_calling/GOI_cohort_variants_CCF.tsv")
ccf_table <- ccf_table %>% mutate(mutation_type = toupper(snv_indel)) # homogenize mutation type between GOI and TIL patients

# Name patients paper
patients_GOI_short <- c("GOI-01", "GOI-02", "GOI-03", "GOI-04", "GOI-05", "GOI-06", "GOI-07", "GOI-08")

# Summary table NSM FrTu
summary_NSM_FrTu <- ccf_table %>% filter(variant_calling %in% c("FrTu_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(NSM = n(), median_tVAF = median(as.numeric(vaf_FrTu)))
colnames(summary_NSM_FrTu) <- c("patient", "NSM", "median_tVAF")
summary_NSM_FrTu$patient <- patients_GOI
summary_NSM_FrTu <- full_join(data.frame(patient = patients_GOI), summary_NSM_FrTu, by = "patient")
summary_NSM_FrTu[is.na(summary_NSM_FrTu)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table SNV FrTu
summary_SNV_FrTu <- ccf_table %>% filter(mutation_type == "SNV", variant_calling %in% c("FrTu_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(SNV = n(), median_tVAF = median(as.numeric(vaf_FrTu)))
colnames(summary_SNV_FrTu) <- c("patient", "SNV", "median_tVAF")
summary_SNV_FrTu$patient <- patients_GOI
summary_SNV_FrTu <- full_join(data.frame(patient = patients_GOI), summary_SNV_FrTu, by = "patient")
summary_SNV_FrTu[is.na(summary_SNV_FrTu)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table INDEL FrTu
summary_INDEL_FrTu <- ccf_table %>% filter(mutation_type == "INDEL", variant_calling %in% c("FrTu_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(INDEL = n(), median_tVAF = median(as.numeric(vaf_FrTu)))
colnames(summary_INDEL_FrTu) <- c("patient", "INDEL", "median_tVAF")
summary_INDEL_FrTu <- full_join(data.frame(patient = patients_GOI_short), summary_INDEL_FrTu, by = "patient")
summary_INDEL_FrTu$patient <- patients_GOI
summary_INDEL_FrTu <- full_join(data.frame(patient = patients_GOI), summary_INDEL_FrTu, by = "patient")
summary_INDEL_FrTu[is.na(summary_INDEL_FrTu)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table NSM cfDNA
summary_NSM_cfDNA <- ccf_table %>% filter(variant_calling %in% c("cfDNA_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(NSM = n(), median_tVAF = median(as.numeric(vaf_cfDNA)))
colnames(summary_NSM_cfDNA) <- c("patient", "NSM", "median_tVAF")
summary_NSM_cfDNA$patient <- patients_GOI
summary_NSM_cfDNA <- full_join(data.frame(patient = patients_GOI), summary_NSM_cfDNA, by = "patient")
summary_NSM_cfDNA[is.na(summary_NSM_cfDNA)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table SNV cfDNA
summary_SNV_cfDNA <- ccf_table %>% filter(mutation_type == "SNV", variant_calling %in% c("cfDNA_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(SNV = n(), median_tVAF = median(as.numeric(vaf_cfDNA)))
colnames(summary_SNV_cfDNA) <- c("patient", "SNV", "median_tVAF")
summary_SNV_cfDNA$patient <- patients_GOI
summary_SNV_cfDNA <- full_join(data.frame(patient = patients_GOI), summary_SNV_cfDNA, by = "patient")
summary_SNV_cfDNA[is.na(summary_SNV_cfDNA)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table INDEL cfDNA
summary_INDEL_cfDNA <- ccf_table %>% filter(mutation_type == "INDEL", variant_calling %in% c("cfDNA_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(INDEL = n(), median_tVAF = median(as.numeric(vaf_cfDNA)))
colnames(summary_INDEL_cfDNA) <- c("patient", "INDEL", "median_tVAF")
summary_INDEL_cfDNA <- full_join(data.frame(patient = patients_GOI_short), summary_INDEL_cfDNA, by = "patient")
summary_INDEL_cfDNA$patient <- patients_GOI
summary_INDEL_cfDNA <- full_join(data.frame(patient = patients_GOI), summary_INDEL_cfDNA, by = "patient")
summary_INDEL_cfDNA[is.na(summary_INDEL_cfDNA)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Merge tables
summary_NSM <- summary_NSM_FrTu %>% left_join(summary_NSM_cfDNA, by = "patient", suffix = c("_FrTu", "_cfDNA"))
summary_NSM_long <- summary_NSM %>%
  pivot_longer(cols = c(NSM_cfDNA, NSM_FrTu), 
               names_to = "dna_source", 
               values_to = "NSM") %>%
  mutate(dna_source = ifelse(dna_source == "NSM_FrTu", "FrTu", "cfDNA")) %>%
  left_join(summary_NSM %>%
              pivot_longer(cols = c(median_tVAF_cfDNA, median_tVAF_FrTu), 
                           names_to = "dna_source", 
                           values_to = "median_tVAF") %>%
              mutate(dna_source = ifelse(dna_source == "median_tVAF_FrTu", "FrTu", "cfDNA")),
            by = c("patient", "dna_source")) %>% dplyr::select(patient, dna_source,NSM, median_tVAF)

summary_SNV <- summary_SNV_FrTu %>% left_join(summary_SNV_cfDNA, by = "patient", suffix = c("_FrTu", "_cfDNA"))
summary_SNV_long <- summary_SNV %>%
  pivot_longer(cols = c(SNV_cfDNA, SNV_FrTu), 
               names_to = "dna_source", 
               values_to = "SNV") %>%
  mutate(dna_source = ifelse(dna_source == "SNV_FrTu", "FrTu", "cfDNA")) %>%
  left_join(summary_SNV %>%
              pivot_longer(cols = c(median_tVAF_cfDNA, median_tVAF_FrTu), 
                           names_to = "dna_source", 
                           values_to = "median_tVAF") %>%
              mutate(dna_source = ifelse(dna_source == "median_tVAF_FrTu", "FrTu", "cfDNA")),
            by = c("patient", "dna_source")) %>% dplyr::select(patient, dna_source,SNV, median_tVAF)

summary_INDEL <- summary_INDEL_FrTu %>% left_join(summary_INDEL_cfDNA, by = "patient", suffix = c("_FrTu", "_cfDNA"))
summary_INDEL_long <- summary_INDEL %>%
  pivot_longer(cols = c(INDEL_cfDNA, INDEL_FrTu), 
               names_to = "dna_source", 
               values_to = "INDEL") %>%
  mutate(dna_source = ifelse(dna_source == "INDEL_FrTu", "FrTu", "cfDNA")) %>%
  left_join(summary_INDEL %>%
              pivot_longer(cols = c(median_tVAF_cfDNA, median_tVAF_FrTu), 
                           names_to = "dna_source", 
                           values_to = "median_tVAF") %>%
              mutate(dna_source = ifelse(dna_source == "median_tVAF_FrTu", "FrTu", "cfDNA")),
            by = c("patient", "dna_source")) %>% dplyr::select(patient, dna_source,INDEL, median_tVAF)

# metadata
meta <- metadata %>% dplyr::filter(Sample_ID %in% patients_GOI)
# NSMs
annot_NSM_vaf_df <- summary_NSM_long
snv_indel_mat <- summary_SNV_long %>%
    dplyr::select(patient, dna_source, SNV) %>%
    left_join(summary_INDEL_long %>% dplyr::select(patient, dna_source, INDEL), by = c("patient", "dna_source")) %>%
    dplyr::filter(patient %in% patients)
snv_indel_mat[is.na(snv_indel_mat)] <- 0 # replace NAs by 0 when no INDELs in patient
snv_indel_mat <- as.matrix(snv_indel_mat %>% dplyr::select(-c(patient, dna_source)))
# Apply a cap of 200 to matrix (to sum SNV+INDEL but respect proportions)
# Capping function
cap_and_transform <- function(row, max_sum = 200) {
    if (all(is.na(row))) {
        return(row)  # Return the row unchanged if it only contains NA
    }
    
    total <- sum(row, na.rm = TRUE)  # Ignore NAs in the sum
    if (total > max_sum) {
        factor <- max_sum / total
        row[!is.na(row)] <- row[!is.na(row)] * factor  # Scale only non-NA values
    }
    
    return(row)
}
# Apply transformation to each row
transformed_mat <- t(apply(snv_indel_mat, 1, cap_and_transform))

# color for annot (VAF, TF, target lesion sum)
col_vaf <- colorRamp2(c(5, 25), c("white", "#FF3E96"))

tumor_group_colors <- c(
    GU = "#FF6F00FF", Lung = "#C71000FF", "H&N" = "#008EA0FF",
    Mesothelioma = "#8A4198FF", Skin = "#A5927D", GI_CRC = "#FF6348FF",
    GI_nonCRC = "#84D7E1FF", Breast = "#FF95A8FF", "NET/Thyroid" = "#3D3B25FF",
    "Bone and Soft Tissue Tumors / Craniovertebral Tumors" = "#ADE2D0FF",
    Gyn = "#1A5354FF", "Sarcoma/Unk" = "#3F4041FF",
    "NA" = "gray"  # Add explicit color for NA values
)

# Create a vector for NSM numbers interleaving with empty strings, to annotate every other column
NSM_annot <- rep("", length(annot_NSM_vaf_df$NSM) * 2) # Preallocate a vector with empty strings
NSM_annot[seq(2, length(NSM_annot), 2)] <- annot_NSM_vaf_df$NSM # Fill every odd index with the original values

# Same for RIO patient code
RIO_annot <- rep("", length(meta$RIO_ID) * 2) # Preallocate a vector with empty strings
RIO_annot[seq(1, length(RIO_annot), 2)] <- meta$RIO_ID # Fill every odd index with the original values

# Annot DNA source and Allele
annot_DNA <- rep(c("cfDNA", "FrTu"), each = 2, times = 8)
annot_allele <- rep(c("A", "B"), times = 16)

column_ha <- HeatmapAnnotation(
    # "360RIO" = anno_text(RIO_annot, location = 0.1, just = "left", gp = gpar(fontsize = 10, col = "grey50"), show_name = TRUE),
	"TMB_txt" = anno_text(NSM_annot, location = 0.1, just = "left", gp = gpar(fontsize = 10, col = "grey30")),
    "TMB" = anno_barplot(transformed_mat[rep(1:nrow(snv_indel_mat), each = 2), ], bar_width = 1, gp = gpar(fill = c("#00C5CD", "blue"), col = c("#00C5CD", "blue"))),
    "Median tVAF" = rep(annot_NSM_vaf_df$median_tVAF * 100, each = 2),
	"SCNA (% of genome)" = rep(percent$scna_percent, each = 2),
    "Tumor Group" = rep(meta$Tumor_group, each = 4),
	"DNA source" = annot_DNA, 
	"Allele" = annot_allele,
    col = list(`Median tVAF` = col_vaf, `Tumor Group` = tumor_group_colors, "DNA source" = c("cfDNA" = "#FCC557", "FrTu" = "#D9D8D4"), "Allele" = c("A" = "grey50", "B" = "grey85"), `SCNA (% of genome)` = col_percent_scna),
    annotation_name_side = "left", annotation_name_gp = gpar(col = "grey20", fontsize = 10),
	simple_anno_size = unit(0.5, "cm")
)

TMB_legend <- Legend(labels = c("SNV", "INDEL"), title = "TMB", legend_gp = gpar(fill = c("#00C5CD", "blue")))

# Order columns
# GOI-01 to TIL015
order_columns <- meta %>%
    pull(Sample_ID)
# # By NSM
# order_columns <- annot_NSM_vaf_df %>%
#     arrange(NSM) %>%
#     pull(patient)
# #  By Tumor Group
# order_columns <- meta %>%
#     arrange(Tumor_group) %>%
#     pull(Sample_ID)
# #  By TF
# order_columns <- meta %>%
#     arrange(TF_value) %>%
#     pull(Sample_ID)
# #  By Median tVAF
# order_columns <- annot_NSM_vaf_df %>%
#     arrange(median_tVAF) %>%
#     pull(patient)

heatmap_colors <- structure(c("#00868B", "grey98 ", "#B77FE2", "#7D26CD"), names = c("0", "1", "2", "3"))
mat_GOI <- pmin(mat_GOI, 3)
mat_GOI <- round(mat_GOI, 0)

# change labels patients: 
patient_label <- gsub("GOIGROS0", "GOI-", order_columns)
patient_label <- gsub("GOI-08", "GOI-06", patient_label)
patient_label <- gsub("Motricolor002", "GOI-05", patient_label)
patient_label <- gsub("TIL012", "GOI-07", patient_label)
patient_label <- gsub("TIL015", "GOI-08", patient_label)


hm <- Heatmap(mat_GOI,
    name = "Allelic Copy Number", top_annotation = column_ha, col = heatmap_colors,
    row_split = chr, cluster_rows = FALSE, cluster_columns = FALSE, column_split = factor(rep(patients_GOI, each = 4), levels = order_columns, labels = patient_label),
    show_column_names = FALSE,
    # column_title = NULL,
    column_title_rot = 90, column_title_gp = gpar(fontsize = 10),
    row_title_rot = 0, row_title_gp = gpar(fontsize = 7), border = TRUE,
    row_gap = unit(0, "points"), column_gap = unit(0, "points"), border_gp = gpar(col = "grey50", lwd = 0.5),
    heatmap_legend_param = list(at = c("0", "1", "2", "3"), labels = c("0", "1", "2", "3+"))
)
pdf("heatmap_GOI_variant_calling.pdf", width = 7, height = 6)
draw(hm, annotation_legend_list = list(TMB_legend), merge_legend = FALSE)
dev.off()
```

#### Dna Presence Heatmap
```{r}
set.seed(4)
# ccf_table load (Dna Presence)
ccf_table <- fread("/Users/plevy/Library/CloudStorage/OneDrive-VHIO/labagros/pierre/proj/collab/andrea/CCF_plots/dna_presence/GOI_cohort_variants_CCF.tsv")
ccf_table <- ccf_table %>% mutate(mutation_type = toupper(snv_indel)) # homogenize mutation type between GOI and TIL patients

# Name patients paper
patients_GOI_short <- c("GOI-01", "GOI-02", "GOI-03", "GOI-04", "GOI-05", "GOI-06", "GOI-07", "GOI-08")

# Summary table NSM FrTu
summary_NSM_FrTu <- ccf_table %>% filter(dna_presence %in% c("FrTu_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(NSM = n(), median_tVAF = median(as.numeric(vaf_FrTu)))
colnames(summary_NSM_FrTu) <- c("patient", "NSM", "median_tVAF")
summary_NSM_FrTu$patient <- patients_GOI
summary_NSM_FrTu <- full_join(data.frame(patient = patients_GOI), summary_NSM_FrTu, by = "patient")
summary_NSM_FrTu[is.na(summary_NSM_FrTu)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table SNV FrTu
summary_SNV_FrTu <- ccf_table %>% filter(mutation_type == "SNV", dna_presence %in% c("FrTu_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(SNV = n(), median_tVAF = median(as.numeric(vaf_FrTu)))
colnames(summary_SNV_FrTu) <- c("patient", "SNV", "median_tVAF")
summary_SNV_FrTu$patient <- patients_GOI
summary_SNV_FrTu <- full_join(data.frame(patient = patients_GOI), summary_SNV_FrTu, by = "patient")
summary_SNV_FrTu[is.na(summary_SNV_FrTu)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table INDEL FrTu
summary_INDEL_FrTu <- ccf_table %>% filter(mutation_type == "INDEL", dna_presence %in% c("FrTu_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(INDEL = n(), median_tVAF = median(as.numeric(vaf_FrTu)))
colnames(summary_INDEL_FrTu) <- c("patient", "INDEL", "median_tVAF")
summary_INDEL_FrTu <- full_join(data.frame(patient = patients_GOI_short), summary_INDEL_FrTu, by = "patient")
summary_INDEL_FrTu$patient <- patients_GOI
summary_INDEL_FrTu <- full_join(data.frame(patient = patients_GOI), summary_INDEL_FrTu, by = "patient")
summary_INDEL_FrTu[is.na(summary_INDEL_FrTu)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table NSM cfDNA
summary_NSM_cfDNA <- ccf_table %>% filter(dna_presence %in% c("cfDNA_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(NSM = n(), median_tVAF = median(as.numeric(vaf_cfDNA)))
colnames(summary_NSM_cfDNA) <- c("patient", "NSM", "median_tVAF")
summary_NSM_cfDNA$patient <- patients_GOI
summary_NSM_cfDNA <- full_join(data.frame(patient = patients_GOI), summary_NSM_cfDNA, by = "patient")
summary_NSM_cfDNA[is.na(summary_NSM_cfDNA)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table SNV cfDNA
summary_SNV_cfDNA <- ccf_table %>% filter(mutation_type == "SNV", dna_presence %in% c("cfDNA_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(SNV = n(), median_tVAF = median(as.numeric(vaf_cfDNA)))
colnames(summary_SNV_cfDNA) <- c("patient", "SNV", "median_tVAF")
summary_SNV_cfDNA$patient <- patients_GOI
summary_SNV_cfDNA <- full_join(data.frame(patient = patients_GOI), summary_SNV_cfDNA, by = "patient")
summary_SNV_cfDNA[is.na(summary_SNV_cfDNA)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Summary table INDEL cfDNA
summary_INDEL_cfDNA <- ccf_table %>% filter(mutation_type == "INDEL", dna_presence %in% c("cfDNA_only", "Shared"), coding_consequence == "non_synonymous") %>%
    distinct(sample, CHROM, POS, REF, ALT, .keep_all = TRUE) %>%
    group_by(sample) %>%
    summarise(INDEL = n(), median_tVAF = median(as.numeric(vaf_cfDNA)))
colnames(summary_INDEL_cfDNA) <- c("patient", "INDEL", "median_tVAF")
summary_INDEL_cfDNA <- full_join(data.frame(patient = patients_GOI_short), summary_INDEL_cfDNA, by = "patient")
summary_INDEL_cfDNA$patient <- patients_GOI
summary_INDEL_cfDNA <- full_join(data.frame(patient = patients_GOI), summary_INDEL_cfDNA, by = "patient")
summary_INDEL_cfDNA[is.na(summary_INDEL_cfDNA)] <- 0 # replace NA by 0. NAs here mean no mutation in the VCF file.

# Merge tables
summary_NSM <- summary_NSM_FrTu %>% left_join(summary_NSM_cfDNA, by = "patient", suffix = c("_FrTu", "_cfDNA"))
summary_NSM_long <- summary_NSM %>%
  pivot_longer(cols = c(NSM_cfDNA, NSM_FrTu), 
               names_to = "dna_source", 
               values_to = "NSM") %>%
  mutate(dna_source = ifelse(dna_source == "NSM_FrTu", "FrTu", "cfDNA")) %>%
  left_join(summary_NSM %>%
              pivot_longer(cols = c(median_tVAF_cfDNA, median_tVAF_FrTu), 
                           names_to = "dna_source", 
                           values_to = "median_tVAF") %>%
              mutate(dna_source = ifelse(dna_source == "median_tVAF_FrTu", "FrTu", "cfDNA")),
            by = c("patient", "dna_source")) %>% dplyr::select(patient, dna_source,NSM, median_tVAF)

summary_SNV <- summary_SNV_FrTu %>% left_join(summary_SNV_cfDNA, by = "patient", suffix = c("_FrTu", "_cfDNA"))
summary_SNV_long <- summary_SNV %>%
  pivot_longer(cols = c(SNV_cfDNA, SNV_FrTu), 
               names_to = "dna_source", 
               values_to = "SNV") %>%
  mutate(dna_source = ifelse(dna_source == "SNV_FrTu", "FrTu", "cfDNA")) %>%
  left_join(summary_SNV %>%
              pivot_longer(cols = c(median_tVAF_cfDNA, median_tVAF_FrTu), 
                           names_to = "dna_source", 
                           values_to = "median_tVAF") %>%
              mutate(dna_source = ifelse(dna_source == "median_tVAF_FrTu", "FrTu", "cfDNA")),
            by = c("patient", "dna_source")) %>% dplyr::select(patient, dna_source,SNV, median_tVAF)

summary_INDEL <- summary_INDEL_FrTu %>% left_join(summary_INDEL_cfDNA, by = "patient", suffix = c("_FrTu", "_cfDNA"))
summary_INDEL_long <- summary_INDEL %>%
  pivot_longer(cols = c(INDEL_cfDNA, INDEL_FrTu), 
               names_to = "dna_source", 
               values_to = "INDEL") %>%
  mutate(dna_source = ifelse(dna_source == "INDEL_FrTu", "FrTu", "cfDNA")) %>%
  left_join(summary_INDEL %>%
              pivot_longer(cols = c(median_tVAF_cfDNA, median_tVAF_FrTu), 
                           names_to = "dna_source", 
                           values_to = "median_tVAF") %>%
              mutate(dna_source = ifelse(dna_source == "median_tVAF_FrTu", "FrTu", "cfDNA")),
            by = c("patient", "dna_source")) %>% dplyr::select(patient, dna_source,INDEL, median_tVAF)

# metadata
meta <- metadata %>% dplyr::filter(Sample_ID %in% patients_GOI)
# NSMs
annot_NSM_vaf_df <- summary_NSM_long
snv_indel_mat <- summary_SNV_long %>%
    dplyr::select(patient, dna_source, SNV) %>%
    left_join(summary_INDEL_long %>% dplyr::select(patient, dna_source, INDEL), by = c("patient", "dna_source")) %>%
    dplyr::filter(patient %in% patients)
snv_indel_mat[is.na(snv_indel_mat)] <- 0 # replace NAs by 0 when no INDELs in patient
snv_indel_mat <- as.matrix(snv_indel_mat %>% dplyr::select(-c(patient, dna_source)))
# Apply a cap of 200 to matrix (to sum SNV+INDEL but respect proportions)
# Capping function
cap_and_transform <- function(row, max_sum = 200) {
    if (all(is.na(row))) {
        return(row)  # Return the row unchanged if it only contains NA
    }
    
    total <- sum(row, na.rm = TRUE)  # Ignore NAs in the sum
    if (total > max_sum) {
        factor <- max_sum / total
        row[!is.na(row)] <- row[!is.na(row)] * factor  # Scale only non-NA values
    }
    
    return(row)
}
# Apply transformation to each row
transformed_mat <- t(apply(snv_indel_mat, 1, cap_and_transform))

# color for annot (VAF, TF, target lesion sum)
col_vaf <- colorRamp2(c(5, 25), c("white", "#FF3E96"))

tumor_group_colors <- c(
    GU = "#FF6F00FF", Lung = "#C71000FF", "H&N" = "#008EA0FF",
    Mesothelioma = "#8A4198FF", Skin = "#A5927D", GI_CRC = "#FF6348FF",
    GI_nonCRC = "#84D7E1FF", Breast = "#FF95A8FF", "NET/Thyroid" = "#3D3B25FF",
    "Bone and Soft Tissue Tumors / Craniovertebral Tumors" = "#ADE2D0FF",
    Gyn = "#1A5354FF", "Sarcoma/Unk" = "#3F4041FF",
    "NA" = "gray"  # Add explicit color for NA values
)

# Create a vector for NSM numbers interleaving with empty strings, to annotate every other column
NSM_annot <- rep("", length(annot_NSM_vaf_df$NSM) * 2) # Preallocate a vector with empty strings
NSM_annot[seq(2, length(NSM_annot), 2)] <- annot_NSM_vaf_df$NSM # Fill every odd index with the original values

# Same for RIO patient code
RIO_annot <- rep("", length(meta$RIO_ID) * 2) # Preallocate a vector with empty strings
RIO_annot[seq(1, length(RIO_annot), 2)] <- meta$RIO_ID # Fill every odd index with the original values

# Annot DNA source and Allele
annot_DNA <- rep(c("cfDNA", "FrTu"), each = 2, times = 8)
annot_allele <- rep(c("A", "B"), times = 16)

column_ha <- HeatmapAnnotation(
    # "360RIO" = anno_text(RIO_annot, location = 0.1, just = "left", gp = gpar(fontsize = 10, col = "grey50"), show_name = TRUE),
	"TMB_txt" = anno_text(NSM_annot, location = 0.1, just = "left", gp = gpar(fontsize = 10, col = "grey30")),
    "TMB" = anno_barplot(transformed_mat[rep(1:nrow(snv_indel_mat), each = 2), ], bar_width = 1, gp = gpar(fill = c("#00C5CD", "blue"), col = c("#00C5CD", "blue"))),
    "Median tVAF" = rep(annot_NSM_vaf_df$median_tVAF * 100, each = 2),
	"SCNA (% of genome)" = rep(percent$scna_percent, each = 2),
    "Tumor Group" = rep(meta$Tumor_group, each = 4),
	"DNA source" = annot_DNA, 
	"Allele" = annot_allele,
    col = list(`Median tVAF` = col_vaf, `Tumor Group` = tumor_group_colors, "DNA source" = c("cfDNA" = "#FCC557", "FrTu" = "#D9D8D4"), "Allele" = c("A" = "grey50", "B" = "grey85"), `SCNA (% of genome)` = col_percent_scna),
    annotation_name_side = "left", annotation_name_gp = gpar(col = "grey20", fontsize = 10),
	simple_anno_size = unit(0.5, "cm")
)

TMB_legend <- Legend(labels = c("SNV", "INDEL"), title = "TMB", legend_gp = gpar(fill = c("#00C5CD", "blue")))

# Order columns
# GOI-01 to TIL015
order_columns <- meta %>%
    pull(Sample_ID)
# # By NSM
# order_columns <- annot_NSM_vaf_df %>%
#     arrange(NSM) %>%
#     pull(patient)
# #  By Tumor Group
# order_columns <- meta %>%
#     arrange(Tumor_group) %>%
#     pull(Sample_ID)
# #  By TF
# order_columns <- meta %>%
#     arrange(TF_value) %>%
#     pull(Sample_ID)
# #  By Median tVAF
# order_columns <- annot_NSM_vaf_df %>%
#     arrange(median_tVAF) %>%
#     pull(patient)

heatmap_colors <- structure(c("#00868B", "grey98 ", "#B77FE2", "#7D26CD"), names = c("0", "1", "2", "3"))
mat_GOI <- pmin(mat_GOI, 3)
mat_GOI <- round(mat_GOI, 0)

# change labels patients: 
patient_label <- gsub("GOIGROS0", "GOI-", order_columns)
patient_label <- gsub("GOI-08", "GOI-06", patient_label)
patient_label <- gsub("Motricolor002", "GOI-05", patient_label)
patient_label <- gsub("TIL012", "GOI-07", patient_label)
patient_label <- gsub("TIL015", "GOI-08", patient_label)


hm <- Heatmap(mat_GOI,
    name = "Allelic Copy Number", top_annotation = column_ha, col = heatmap_colors,
    row_split = chr, cluster_rows = FALSE, cluster_columns = FALSE, column_split = factor(rep(patients_GOI, each = 4), levels = order_columns, labels = patient_label),
    show_column_names = FALSE,
    # column_title = NULL,
    column_title_rot = 90, column_title_gp = gpar(fontsize = 10),
    row_title_rot = 0, row_title_gp = gpar(fontsize = 7), border = TRUE,
    row_gap = unit(0, "points"), column_gap = unit(0, "points"), border_gp = gpar(col = "grey50", lwd = 0.5),
    heatmap_legend_param = list(at = c("0", "1", "2", "3"), labels = c("0", "1", "2", "3+"))
)
pdf("heatmap_GOI_dna_presence.pdf", width = 7, height = 6)
draw(hm, annotation_legend_list = list(TMB_legend), merge_legend = FALSE)
dev.off()
```


