#!/bin/bash

if [ $# -eq 0  ] || [ $1 == "-h" ] || [ $1 == "--help" ]
then { printf "
 Usage:
 \$1=PATIENT
 \$2=TUMOR_SAMPLE_NAME
 \$3=THREADS
 \$4=SEX (XX or XY)
 \$5=TBAM_PATH (path to tumor bam)
 \$6=NBAM_PATH (path to normal bam)
 \$7=OUTDIR
 \$8=DNA (cfDNA or FrTu)
 \$9=GENOME (hg19 or hg38)
 \$10=BED_PATH (optional, use 'NULL' or leave empty to analyze whole genome)
 \$11=SKIP_NORMAL_PROCESS (TRUE or FALSE)
 "; exit 1; }
fi

set -uex

# VARIABLES
PATIENT=${1}
TUMOR_SAMPLE_NAME=${2}
THREADS=${3}
SEX=${4}
TBAM_PATH=${5}
NBAM_PATH=${6}
OUTDIR=${7}
DNA=${8}
GENOME=${9}
BED_PATH=${10:-"NULL"}  # Default to "NULL" if not provided
SKIP_NORMAL_PROCESS=${11:-"FALSE"}  # Default to "FALSE" if not provided

# ASCAT #########################################################################

mkdir -p ${OUTDIR}

Rscript ascat_${DNA}.R \
${TBAM_PATH} \
${NBAM_PATH} \
${PATIENT} \
${TUMOR_SAMPLE_NAME} \
${BED_PATH} \
ascat_refs \
${THREADS} \
${SEX} \
${GENOME} \
${OUTDIR} \
${SKIP_NORMAL_PROCESS}
