#!/bin/bash

if [ $# -eq 0  ] || [ $1 == "-h" ] || [ $1 == "--help" ]
then { printf "
 Usage:
 \$1=PATIENT
 \$2=TUMOR_SAMPLE_NAME
 \$3=THREADS
 \$4=SEX (XX or XY)
 \$5=TBAM_PATH (path to tumor bam)
 \$6=NBAM_PATH (path to normal bam)
 \$7=OUTDIR
 \$8=DNA (cfDNA or FrTu)
 \$9=GENOME (hg19 or hg38)
 \$10=BED_PATH (optional, use 'NULL' or leave empty to analyze whole genome)
 \$11=SKIP_NORMAL_PROCESS (TRUE or FALSE)
 "; exit 1; }
fi

set -uex

# VARIABLES
PATIENT=${1}
TUMOR_SAMPLE_NAME=${2}
THREADS=${3}
SEX=${4}
TBAM_PATH=$(realpath "${5}")
NBAM_PATH=$(realpath "${6}")
OUTDIR=${7}
DNA=${8}
GENOME=${9}
BED_PATH_RAW=${10:-"NULL"}  # Default to "NULL" if not provided
SKIP_NORMAL_PROCESS=${11:-"FALSE"}  # Default to "FALSE" if not provided

TBAM_DIR=$(dirname ${TBAM_PATH})
NBAM_DIR=$(dirname ${NBAM_PATH})
TBAM=$(basename ${TBAM_PATH})
NBAM=$(basename ${NBAM_PATH})

# Handle optional BED file
if [[ "${BED_PATH_RAW}" == "NULL" || "${BED_PATH_RAW}" == "" ]]; then
    BED_MOUNT=""
    BED_ARG="NULL"
else
    BED_PATH=$(realpath "${BED_PATH_RAW}")
    BED_DIR=$(dirname ${BED_PATH})
    BED=$(basename ${BED_PATH})
    BED_MOUNT="-v ${BED_DIR}:/bed_dir"
    BED_ARG="/bed_dir/${BED}"
fi

# ASCAT #########################################################################

mkdir -p ${OUTDIR}

docker run --rm \
-v ${TBAM_DIR}:/tbam_dir \
-v ${NBAM_DIR}:/nbam_dir \
${BED_MOUNT} \
-v ${OUTDIR}:/ascat \
-v ${PWD}:/scripts \
-v $(realpath "ascat_refs"):/ref \
-w /ascat \
    plev/ascat:3.1.2 \
    Rscript /scripts/ascat_${DNA}.R \
/tbam_dir/${TBAM} \
/nbam_dir/${NBAM} \
${PATIENT} \
${TUMOR_SAMPLE_NAME} \
${BED_ARG} \
/ref \
${THREADS} \
${SEX} \
${GENOME} \
/ascat \
${SKIP_NORMAL_PROCESS}
